# Generated by Django 5.1.7 on 2025-08-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('가방', '가방'), ('귀금속', '귀금속'), ('의류', '의류'), ('전자기기', '전자기기'), ('지갑', '지갑'), ('컴퓨터', '컴퓨터'), ('카드', '카드'), ('현금', '현금'), ('휴대폰', '휴대폰'), ('문서/서류', '문서/서류'), ('악기', '악기'), ('스포츠용품', '스포츠용품'), ('신분증', '신분증'), ('책/노트', '책/노트'), ('기타', '기타')], default='기타', max_length=50)),
                ('found_location', models.CharField(max_length=200)),
                ('found_date', models.DateField()),
                ('is_returned', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('보관 중', '보관 중'), ('소유자 반환', '소유자 반환')], default='보관 중', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('login', '로그인 문제'), ('lost', '분실물 등록/조회'), ('account', '계정 관련'), ('other', '기타')], default='other', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('answered', '답변 완료'), ('closed', '종료')], default='pending', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('가방', '가방'), ('귀금속', '귀금속'), ('의류', '의류'), ('전자기기', '전자기기'), ('지갑', '지갑'), ('컴퓨터', '컴퓨터'), ('카드', '카드'), ('현금', '현금'), ('휴대폰', '휴대폰'), ('문서/서류', '문서/서류'), ('악기', '악기'), ('스포츠용품', '스포츠용품'), ('신분증', '신분증'), ('책/노트', '책/노트'), ('기타', '기타')], default='기타', max_length=50)),
                ('lost_location', models.CharField(max_length=200)),
                ('lost_date_start', models.DateField(blank=True, null=True)),
                ('lost_date_end', models.DateField(blank=True, null=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveBigIntegerField()),
            ],
        ),
    ]
