# Generated by Django 5.2.3 on 2025-07-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('카드', '카드'), ('지갑', '지갑'), ('전자기기', '전자기기'), ('의류', '의류'), ('가방', '가방'), ('신발', '신발'), ('문서/서류', '문서/서류'), ('귀금속', '귀금속'), ('악기', '악기'), ('책/노트', '책/노트'), ('스포츠 용품', '스포츠 용품'), ('신분증', '신분증'), ('현금', '현금'), ('기타', '기타')], default='기타', max_length=50)),
                ('found_location', models.CharField(max_length=200)),
                ('found_date', models.DateField()),
                ('is_returned', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('카드', '카드'), ('지갑', '지갑'), ('전자기기', '전자기기'), ('의류', '의류'), ('가방', '가방'), ('신발', '신발'), ('문서/서류', '문서/서류'), ('귀금속', '귀금속'), ('악기', '악기'), ('책/노트', '책/노트'), ('스포츠 용품', '스포츠 용품'), ('신분증', '신분증'), ('현금', '현금'), ('기타', '기타')], default='기타', max_length=50)),
                ('lost_contact', models.CharField(blank=True, max_length=20)),
                ('lost_location', models.CharField(max_length=200)),
                ('lost_date', models.DateField()),
                ('is_claimed', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
    ]
