# Generated by Django 5.2.3 on 2025-06-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('lost_contact', models.CharField(blank=True, max_length=20)),
                ('lost_location', models.CharField(max_length=200)),
                ('lost_date', models.DateField()),
                ('found_location', models.CharField(max_length=200)),
                ('found_date', models.DateField()),
                ('is_claimed', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
            ],
        ),
    ]
