# Generated by Django 5.1.7 on 2025-08-12 11:12

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('meetagain', '0002_initial'),  # 0001_initial 이후로 맞추면 OK (둘 다 initial이라면 0002로 두기)
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE meetagain_lostitem
            ADD COLUMN IF NOT EXISTS lost_date_start date;

            ALTER TABLE meetagain_lostitem
            ADD COLUMN IF NOT EXISTS lost_date_end date;
            """
        ),
    ]
