# Generated by Django 5.1.7 on 2025-08-12 11:03

from django.db import migrations
import datetime

def backfill_lost_dates(apps, schema_editor):
    LostItem = apps.get_model('meetagain', 'LostItem')
    today = datetime.date.today()

    # 시작일 비어있으면 오늘 날짜로 채움
    LostItem.objects.filter(lost_date_start__isnull=True).update(lost_date_start=today)
    # 종료일 비어있으면 오늘 날짜로 채움
    LostItem.objects.filter(lost_date_end__isnull=True).update(lost_date_end=today)

class Migration(migrations.Migration):

    dependencies = [
        ('meetagain', '0005_backfill_lost_date'),  # 바로 이전 번호로 맞추세요
    ]

    operations = [
        migrations.RunPython(backfill_lost_dates, migrations.RunPython.noop),
    ]