# Generated by Django 5.2.5 on 2025-08-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetagain', '0003_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('login', '로그인 문제'), ('lost', '분실물 등록/조회'), ('account', '계정 관련'), ('other', '기타')], default='other', max_length=20),
        ),
    ]
