# Generated by Django 5.1.7 on 2025-08-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetagain', '0004_backfill_lost_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='lost_date_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='lost_date_start',
            field=models.DateField(blank=True),
        ),
    ]
