# Generated by Django 5.2.5 on 2025-08-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetagain', '0004_inquiry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
