# Generated by Django 5.2.5 on 2025-08-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetagain', '0005_inquiry_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', '대기 중'), ('answered', '답변 완료'), ('closed', '종료')], default='pending', max_length=20),
        ),
    ]
