# Generated by Django 5.1.7 on 2025-08-12 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetagain', '0006_remove_lost_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='lost_location',
        ),
        migrations.AddField(
            model_name='lostitem',
            name='lost_locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=5),
        ),
    ]
