# Generated by Django 5.1.7 on 2025-08-12 15:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetagain', '0007_remove_lostitem_lost_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='lost_locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
