# Generated by Django 5.2.5 on 2025-08-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetagain', '0008_alter_lostitem_lost_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='세부옵션'),
        ),
    ]
