# Generated by Django 5.1.7 on 2025-08-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetagain', '0009_founditem_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='세부옵션'),
        ),
    ]
