# Generated by Django 5.2.5 on 2025-08-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetagain', '0010_lostitem_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
